### Image classifcation with The Perceptron Training Algorithm 

In this project, we try to classify the digits in MNIST data set with perceptron model and its training algorithm. 

Before apply the algorithm, let we remember the structre of a perceptron and the perceptron training algorithm. 

##### The structure of a perceptron

![Perceptron](single_layer_perceptron.png)

The algorithm is

![perceptron_training_algo](perceptron_training_algo.png)

Let start code with Python

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from keras.datasets import mnist

Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [4]:
x_train[0].shape

(28, 28)

In [5]:
y_train[0]

5

In [6]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

Now, we shall set a perceptron. First, we need to create randomized weights. Then, we will update these weigths according to the perceptron learning algorithm. 

In [7]:
def create_weights(data):
    a, b = np.shape(data)
    weights = np.random.rand(784,10)
    #weights = 2*np.random.random((784,10)) - 1
    return weights

In [39]:
a, b = np.shape(x_train[0])

In [8]:
weights = create_weights(x_train[0])

In [9]:
weights

array([[0.53354046, 0.24108981, 0.46661302, ..., 0.06845384, 0.78820726,
        0.08793961],
       [0.39773633, 0.42666004, 0.54469582, ..., 0.38843871, 0.24638733,
        0.0949572 ],
       [0.6355672 , 0.61336934, 0.97578461, ..., 0.60282508, 0.88192019,
        0.87077306],
       ...,
       [0.59499502, 0.81640493, 0.61851585, ..., 0.30931694, 0.1057697 ,
        0.27675742],
       [0.98360971, 0.78888398, 0.60941231, ..., 0.66312765, 0.04060891,
        0.7995623 ],
       [0.02838106, 0.55181874, 0.26565217, ..., 0.22351781, 0.77558831,
        0.1228347 ]])

In [10]:
weights.shape

(784, 10)

In [44]:
first_data = x_train[0].reshape(1,784)

In [45]:
first_data.shape

(1, 784)

In [46]:
def predict(data_point, weights):
    predicted = []
    net_input = np.dot(data_point, weights)
    
    for index in range(0,10):
        if net_input[0][index] > 0:
            predicted.append(1)
        else:
            predicted.append(0)
    return predicted

In [47]:
net_input = np.dot(first_data, weights)

In [48]:
list(net_input[0])

[13681.101499080642,
 13125.84786815466,
 13719.887596033717,
 14209.466886484346,
 13075.765367593074,
 12984.044497335992,
 12899.8465764833,
 14830.79428298864,
 12866.15489835765,
 12471.806434083925]

In [49]:
predict(first_data, weights)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [50]:
def one_number(labels, number):
    return (labels == number)*1

In [51]:
actual = []
for no in range(0,10):
    actual.append(one_number(y_train[0], no))
print(actual)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]


In [61]:
def update(weights, data_point, actual_label, alpha=.1):
    predicted_label = predict(data_point, weights)
    delta_weight = np.zeros(np.shape(weights))
    
    #hata hesaplanir
    error = []
    for index in range(0,10):
        error.append(actual_label[index] - predicted_label[index])
    
    error = np.array(error)
    error = error.reshape(1,10)
    
    #vektorlerin boyutlari goz onunde bulundurularak delta weight hesaplanir
    delta_weight = alpha*data_point.T*error
    
    return delta_weight + weights

In [62]:
update(weights, first_data, actual, 0.1)

array([[0.53354046, 0.24108981, 0.46661302, ..., 0.06845384, 0.78820726,
        0.08793961],
       [0.39773633, 0.42666004, 0.54469582, ..., 0.38843871, 0.24638733,
        0.0949572 ],
       [0.6355672 , 0.61336934, 0.97578461, ..., 0.60282508, 0.88192019,
        0.87077306],
       ...,
       [0.59499502, 0.81640493, 0.61851585, ..., 0.30931694, 0.1057697 ,
        0.27675742],
       [0.98360971, 0.78888398, 0.60941231, ..., 0.66312765, 0.04060891,
        0.7995623 ],
       [0.02838106, 0.55181874, 0.26565217, ..., 0.22351781, 0.77558831,
        0.1228347 ]])

In [63]:
#training fonksiyonu
def train_perceptron(data, labels, weights, alpha = .001, iterations = 10):
    for j in range(0, iterations):
        weights = update(weights, data, labels, alpha)
    return weights

In [64]:
#training fonksiyonu guncellenmis agirlik degerlerini dondurur. 1000 defa tekrarlanir
last_weight = train_perceptron(first_data, actual, weights, 0.001, 1000)

In [66]:
#son guncellenen agirlik ile tahmin yapilir
predict(first_data, last_weight)

[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

In [50]:
def test_perceptron_f(data, labels, weights):
    a,b = np.shape(data)
    predicted = predict(data, weights)
    
    correct = (predicted==labels)*1
    true_pos = np.sum((labels==1)*(correct))
    true_neg = np.sum((labels==0)*(correct))
    
    tp_p = true_pos/float(np.sum(labels))
    print(np.sum(labels))
    tn_p = true_neg/float(a- np.sum(labels))
    
    return true_pos, true_neg, tp_p, tn_p, a